on:
  push:
    branches:
      - master
    paths:
      - "gradle/**"
      - "**.kts"
      - gradle.properties
      - gradlew
      - "**.kt"
      - "**.java"
      - .github/workflows/benchmark.yml
  workflow_dispatch:
jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        benchmark:
          - name: BasicSerialize
            conventional:
              set: MainSer
              mapper: Original
            present:
              set: MainSer
              mapper: Kogera
          - name: BasicDeserialize
            conventional:
              set: MainDeser
              mapper: Original
            present:
              set: MainDeser
              mapper: Kogera
          - name: ValueClassSerialize
            conventional:
              set: WrapperSer
              mapper: Kogera
            present:
              set: ValueClassSer
              mapper: Kogera
          - name: ValueClassSerializeWithJsonKUnbox
            conventional:
              set: WrapperSer
              mapper: Kogera
            present:
              set: ValueClassSerWithJsonKUnbox
              mapper: Kogera
          - name: ValueClassDeserialize
            conventional:
              set: WrapperDeser
              mapper: Kogera
            present:
              set: ValueClassDeser
              mapper: Kogera
        is-single-shot: [true, false]
    timeout-minutes: 60
    name: "${{ matrix.benchmark.name }}-${{ (matrix.is-single-shot && 'ss') || 'thrpt' }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Make report dir
        run: mkdir tmp
      - name: Set up java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Set up gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Benchmark Conventional
        run: |
          ./gradlew jmh -Pmapper=${{ matrix.benchmark.conventional.mapper }} -PbenchmarkSet=${{ matrix.benchmark.conventional.set }} -PisSingleShot=${{ matrix.is-single-shot }} -PfileName=Conventional
      - name: Benchmark Present
        run: |
          ./gradlew jmh -Pmapper=${{ matrix.benchmark.present.mapper }} -PbenchmarkSet=${{ matrix.benchmark.present.set }} -PisSingleShot=${{ matrix.is-single-shot }} -PfileName=Present
      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: "${{ matrix.benchmark.name }}-${{ (matrix.is-single-shot && 'ss') || 'thrpt' }}"
          path: tmp
  update-reports:
    runs-on: ubuntu-latest
    needs: benchmark
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Remove Old Reports
        run: |
          find ./ci-reports/ -type f -name '*.txt' -delete
          find ./ci-reports/ -type f -name '*.csv' -delete
      - name: Download reports
        uses: actions/download-artifact@v4
        with:
          path: ci-reports
      - name: Commit Reports
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Reports
