on:
  push:
    branches:
      - master
    paths:
      - "gradle/**"
      - "**.kts"
      - gradle.properties
      - gradlew
      - "**.kt"
      - "**.java"
      - .github/workflows/benchmark.yml
  workflow_dispatch:
jobs:
  benchmark:
    runs-on: ubuntu-22.04
    timeout-minutes: 1200
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up java
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Remove Old Reports
        run: |
          rm -f ./ci-reports/*.csv
          rm -f ./ci-reports/*.txt
      - name: Original Single Shot
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6.2
          arguments: jmh -Pmapper=Original -PisSingleShot=true -PisOnlyMain=false
      - name: Original Throughput
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6.2
          arguments: jmh -Pmapper=Original -PisSingleShot=false -PisOnlyMain=false
      - name: Original StrictNullCheck Single Shot
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6.2
          arguments: jmh -Pmapper=OriginalStrictNullCheck -PisSingleShot=true -PisOnlyMain=false
      - name: Original StrictNullCheck Throughput
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6.2
          arguments: jmh -Pmapper=OriginalStrictNullCheck -PisSingleShot=false -PisOnlyMain=false
      - name: Kogera Single Shot
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6.2
          arguments: jmh -PisSingleShot=true -PisOnlyMain=false
      - name: Kogera Throughput
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6.2
          arguments: jmh -PisSingleShot=false -PisOnlyMain=false
      - name: Kogera StrictNullCheck Single Shot
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6.2
          arguments: jmh  -Pmapper=KogeraStrictNullCheck -PisSingleShot=true -PisOnlyMain=false
      - name: Kogera StrictNullCheck Throughput
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6.2
          arguments: jmh -Pmapper=KogeraStrictNullCheck -PisSingleShot=false -PisOnlyMain=false
      - name: Update Reports
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Reports
