on:
  push:
    branches:
      - master
    paths:
      - "gradle/**"
      - "**.kts"
      - gradle.properties
      - gradlew
      - "**.kt"
      - "**.java"
      - .github/workflows/benchmark.yml
  workflow_dispatch:
jobs:
  benchmark:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        benchmark:
          - conventional:
              set: MainSer
              mapper: Original
            present:
              set: MainSer
              mapper: Kogera
          - conventional:
              set: MainDeser
              mapper: Original
            present:
              set: MainDeser
              mapper: Kogera
          - conventional:
              set: WrapperSer
              mapper: Kogera
            present:
              set: ValueClassSer
              mapper: Kogera
          - conventional:
              set: WrapperDeser
              mapper: Kogera
            present:
              set: ValueClassDeser
              mapper: Kogera
          - conventional:
              set: StrictNullChecks
              mapper: Original
            present:
              set: StrictNullChecks
              mapper: Kogera
        is-single-shot: [true]
    timeout-minutes: 1200
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up java
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Benchmark Conventional
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6.2
          arguments: |
            jmh
            -Pmapper=${{ matrix.benchmark.conventional.mapper }}
            -PbenchmarkSet=${{ matrix.benchmark.conventional.set }}
            -PisSingleShot=${{ matrix.is-single-shot }}
      - name: Update Reports
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Reports
          skip_fetch: false
          skip_checkout: false
